version: "2.2"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./src:/src"
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7.2-fpm
    volumes:
      - "./src:/src"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
        - ./postgres/var/lib/postgres:/var/lib/postgres
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - db

networks: 
  db: