version: "2.2"
services:
  nginx:
    extends:
      file: ./nginx/docker-compose.yml
      service: nginx
    networks:
        - nginx
    depends_on:
        - "php"
    volumes:
        - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/config/app.vhost:/etc/nginx/conf.d/app.vhost
        - ./nginx/Logs/Nginx:/var/log/nginx
        - ../src/:/var/www/html
    ports:
        - "80:80"
        - "443:443"

  php:
    extends:
      file: ./php/docker-compose.yml
      service: php
    networks:
        - nginx
        - db
    depends_on:
        - "postgres"
    volumes:
        - ../src/:/var/www/html

  postgres:
    extends:
      file: ./postgres/docker-compose.yml
      service: postgres
    networks:
        - db
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=postgres
    volumes:
        - ./postgres/var/lib/postgres:/var/lib/postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - "8080:80"
    depends_on:
      - "postgres"
    networks:
      - db

networks:
  nginx:
  db:
